using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Constants
{
    public const string PLAYER_HIGHSCORE_PLAYERPREF_KEY = "PLAYER_HIGHSCORE_PLAYERPREF_KEY";
    public const string PLAYER_HIGHEST_PLATFORMS_PASSED_PLAYERPREF_KEY = "PLAYER_HIGHEST_PLATFORM_PLAYERPREF_KEY";
    public const string PLAYER_LONGEST_TIME_PLAYERPREF_KEY = "PLAYER_LONGEST_TIME_PLAYERPREF_KEY";
    public const string PLAYER_TOTAL_TIME_PLAYERPREF_KEY = "PLAYER_TOTAL_TIME_PLAYERPREF_KEY";
    public const string PLAYER_TOTAL_PLATFORMS_PASSED_PLAYERPREF_KEY = "PLAYER_TOTAL_PLATFORMS_PASSED_PLAYERPREF_KEY";
    public const string PLAYER_TOTAL_PLATFORMS_HIT_PLAYERPREF_KEY = "PLAYER_TOTAL_PLATFORMS_HIT_PLAYERPREF_KEY";
}
